Repository vutfitdiscord/rubbergod, pull requests merged in 2024-09, with the labels that each got.

#1103 Moderation cog
  cogs/moderation/cog.py
  cogs/moderation/features.py
  cogs/moderation/messages_cz.py
Labels: enhancement

#1104 fix: report missing attachment
  cogs/report/views.py
Labels: bug

#1105 Subscription
  cogs/subscriptions/cog.py
Labels: bug

#1115 fix: using deleted webhook
  cogs/fitwide/cog.py
  features/error.py
Labels: bug

#1117 fix: error.py dead webhook + restore update from login
  cogs/fitwide/cog.py
  cogs/fitwide/messages_cz.py
  features/error.py
Labels: bug

#1118 fix: relation faculty
  features/verify_helper.py
Labels: bug

#1119 fix: ignore muni people, use global session
  cogs/fitwide/cog.py
  database/verification.py
  features/verify_helper.py
Labels: bug

#1123 fix: sorting on teacher update
  cogs/fitwide/features.py
Labels: bug

#1152 feat:create move_category command
  cogs/README.md
  cogs/roles/cog.py
  cogs/roles/messages_cz.py
Labels: enhancement

#1156 Remove local setup from README
  README.md
Labels: documentation
