Repository vutfitdiscord/rubbergod, pull requests merged in 2024-05, with the labels that each got.

#1019 remove mention in pick
  cogs/random/cog.py
Labels: enhancement

#1022 nonetype last_error
  cogs/system/cog.py
  database/error.py
Labels: bug

#1023 Use nice and shiny markdown alerts
  README.md
Labels: documentation

#1026 remove tracking of backup.sql
  .gitignore
Labels: enhancement

#1031 remove blocking requests in gif.py
  cogs/gif/cog.py
  cogs/gif/messages_cz.py
Labels: enhancement

#1034 fix gif wrong author
  cogs/gif/cog.py
Labels: bug

#1036 add holopin automation for badges
  .github/holopin.yml
Labels: enhancement

#1038 wrong send method
  cogs/timeout/features.py
Labels: bug

#1037 add sending/resending messages with attachments
  cogs/message/cog.py
  cogs/message/messages_cz.py
  cogs/message/modals.py
Labels: enhancement

#1045 fix: invalid phrase
  cogs/timeout/cog.py
Labels: bug
