Repository vutfitdiscord/rubbergod, pull requests merged in 2025-03, with the labels that each got.

#1215 Add Prometheus logging
  cogs/README.md
  cogs/prometheus/LICENSE
  cogs/prometheus/README.md
  cogs/prometheus/__init__.py
  cogs/prometheus/cog.py
  cogs/prometheus/features.py
  cogs/prometheus/grafana_dashboard.json
  config/config.template.toml
  docker-compose.yml
  features/logger.py
  init.sh
  requirements.txt
Labels: enhancement

#1218 fix guild is None
  cogs/prometheus/cog.py
  cogs/prometheus/grafana_dashboard.json
Labels: bug

#1220 docs: update `README.md`
  README.md
Labels: documentation, no-deployment

#1223 fix verify visibility in guild
  cogs/verify/cog.py
Labels: bug, no-deployment

#1231 fix None for missing url when NASA API breaks
  cogs/info/features.py
Labels: bug

#1230 feat: rename dropout role to ex-student
  cogs/absolvent/cog.py
  cogs/fitwide/cog.py
  cogs/fitwide/features.py
  cogs/fitwide/messages_cz.py
  features/verification.py
Labels: enhancement, no-deployment

#1234 fix(verify): Fix for repeating mail for VUT API
  features/verify_helper.py
Labels: bug
